### PR TITLE
Update textures to 1.20

### PR DESCRIPTION
**Pull request by BrandonItaly**
Updated textures to 1.20 and fixed broken Ghast Spawn Egg texture

### CODE REVIEW

**Comment by DBTDerpbox** [comment]
im curious, where did you get these from? bedrock?

**Comment by BrandonItaly** [comment]
yes, the textures are from bedrock edition

**Comment by DBTDerpbox** [comment]
Wait did something happen?

Sorry for not accepting this yet, i've been real busy and only now got around to updating the resources again

**Comment by BrandonItaly** [comment]
No worries, I'm going to make an updated pull request for the 1.20.4 textures

**Comment by DBTDerpbox** [comment]
ahh okay

**Pull request closed without merging**
