### PR TITLE
Dutch translations (nl_nl.json)

### PR DESCRIPTION
**Pull request by ixnoahlive**

### CODE REVIEW

**Comment by DBTDerpbox** [comment]
Apparently we've forgotten to add this?
Will review next resource update

**Comment by DBTDerpbox** [comment]
Fails to load due to a typo at line 294, other than that its good to go

**Comment by ixnoahlive** [comment]
whoops, do you need me to fix that bug or did you already fix it ?

**Comment by DBTDerpbox** [comment]
I dealt with it https://github.com/Legacy-Edition-Minigames/Minigame-Resources/commit/b2ea5932a02de177e515bad18271a7e8da9def24

**Pull request merged**
