### PR TITLE
Halloween sky and fog colors

### PR DESCRIPTION
**Pull request by BrandonItaly**
Added Halloween sky and fog colors when using [Polytone](https://modrinth.com/mod/polytone)

### CODE REVIEW

**Comment by S-N00B-1** [comment]
Those colours are already handled by the [Halloween biome.](https://github.com/Legacy-Edition-Minigames/Minigames/blob/battle/world/datapacks/lem.base/data/lem.base/worldgen/biome/halloween.json)

**Comment by BrandonItaly** [comment]
Odd, I'm not seeing the sky colors in game on the halloween map.

**Comment by PixeoGames** [comment]
Check not using Polytone or just using the vanilla client, likely a mod issue

**Comment by BrandonItaly** [comment]
Yeah, seems like it was an issue with Starlight, my apologies.

**Pull request closed without merging**
