### PR TITLE
Update en_us.json

### PR DESCRIPTION
**Pull request by kyrptonaught**
Add more translations for Vote Book

### CODE REVIEW

**Comment by DBTDerpbox** [comment]
Can I ask why a bunch of completely unrelated translations were removed?

I assume just an old version of the file you were working with

**Comment by DBTDerpbox** [comment]
I can fix it manually, just wanting to know if there was some purpose to it

**Comment by kyrptonaught** [comment]
Yeah that was not on purpose

**Comment by DBTDerpbox** [comment]
did you remove the generic version key intentionally? it was used by modtools1

**Comment by kyrptonaught** [comment]
That may have been an accident, but I was using a vanilla key for version instead “mco.version”

**Comment by DBTDerpbox** [comment]
ah, thats fair

**Comment by kyrptonaught** [comment]
This has all the translations I needed for now, but it is missing descriptions for each of the resourcepacks

**Pull request merged**
